#!/usr/bin/env bash
finish() {
    # Fix ownership of new files
    host_uid=$(stat -c '%u:%g' /src)
    chown -R $host_uid /src
}
trap finish EXIT
/usr/bin/ldc2 -mtriple=arm-linux-gnueabihf -gcc=arm-linux-gnueabihf-gcc -L=-L/usr/arm-linux-gnueabihf/lib $@
