#!/usr/bin/env bash
DOCKER_TARGET_TRIPLE=
finish() {
    # Fix ownership of new files
    host_uid=$(stat -c '%u:%g' /src)
    chown -R $host_uid /src
}
trap finish EXIT
/usr/bin/ldc2 -mtriple=${DOCKER_TARGET_TRIPLE} -gcc=${DOCKER_TARGET_TRIPLE}-gcc -L=-L/usr/${DOCKER_TARGET_TRIPLE}/lib $@
